name: TLS version
on:
  workflow_dispatch:
jobs:
  tls-unix:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - name: Check default TLS version on unix systems
        run: curl https://google.com/ --verbose
  tls-windows:
    runs-on: windows-latest
    steps:
      - name: Check TLS version on windows
        run: |
          [Net.ServicePointManager]::SecurityProtocol
