name: TLS version
on:
  workflow_dispatch:
jobs:
  tls-macos:
    runs-on: macos-latest
    steps:
      - name: Check default TLS version on macos
        run: curl https://google.com/ --verbose
  tls-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check default TLS version on ubuntu
        run: curl https://google.com/ --verbose
  tls-windows:
    runs-on: windows-latest
    steps:
      - name: Check TLS version on windows
        run: |
          [Net.ServicePointManager]::SecurityProtocol
